// Created by iWeb 3.0.3 local-build-20120717

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id3" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="348" height="213" style="height: 197px; left: 13px; position: absolute; top: -56px; width: 348px; z-index: 1; "><param name="src" value="Media/logo-mobile-3.m4v" /><param name="controller" value="false" /><param name="autoplay" value="true" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="true" /></object>');}
else if(isiPhone)
{document.write('<object id="id3" type="video/quicktime" width="348" height="213" style="height: 197px; left: 13px; position: absolute; top: -56px; width: 348px; z-index: 1; "><param name="src" value="DD-Mercent_files/logo-mobile.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/logo-mobile-3.m4v"/><param name="controller" value="false"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id3" type="video/quicktime" width="348" height="213" data="Media/logo-mobile-3.m4v" style="height: 197px; left: 13px; position: absolute; top: -56px; width: 348px; z-index: 1; "><param name="src" value="Media/logo-mobile-3.m4v"/><param name="controller" value="false"/><param name="autoplay" value="true"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="true"/></object>');}}
setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,424),url:'DD-Mercent_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'DD-Mercent_files/stroke_1.png'},{rect:new IWRect(1,-1,432,2),url:'DD-Mercent_files/stroke_2.png'},{rect:new IWRect(433,-1,2,2),url:'DD-Mercent_files/stroke_3.png'},{rect:new IWRect(433,1,2,424),url:'DD-Mercent_files/stroke_4.png'},{rect:new IWRect(433,425,2,3),url:'DD-Mercent_files/stroke_5.png'},{rect:new IWRect(1,425,432,3),url:'DD-Mercent_files/stroke_6.png'},{rect:new IWRect(-1,425,2,3),url:'DD-Mercent_files/stroke_7.png'}],new IWSize(434,426)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,428),url:'DD-Mercent_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'DD-Mercent_files/stroke_9.png'},{rect:new IWRect(1,-1,423,2),url:'DD-Mercent_files/stroke_10.png'},{rect:new IWRect(424,-1,2,2),url:'DD-Mercent_files/stroke_11.png'},{rect:new IWRect(424,1,2,428),url:'DD-Mercent_files/stroke_12.png'},{rect:new IWRect(424,429,2,3),url:'DD-Mercent_files/stroke_13.png'},{rect:new IWRect(1,429,423,3),url:'DD-Mercent_files/stroke_14.png'},{rect:new IWRect(-1,429,2,3),url:'DD-Mercent_files/stroke_15.png'}],new IWSize(425,430))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('DD-Mercent_files/DD-MercentMoz.css')
detectBrowser();adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');Widget.onload();fixAllIEPNGs('Media/transparent.gif');applyEffects()}
function onPageUnload()
{Widget.onunload();}
